version: '2'

services:

### Workspace Utilities Container ###########################

    laravel:
        build:
            context: ./laravel
        volumes:
          ### laravel folder
            - ./diendanhoctap:/var/www/html
          ### data mysql folder
            - ./mysql/datadir:/var/lib/mysql
          ### config apache2 server
            - ./config:/etc/apache2/sites-available
        ports:
           - "80:80"
           - "3306:3306"
           - "8080:8080"
        tty: true
           


